# Generated by Django 4.0.5 on 2022-07-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insalon_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insProd_Name', models.CharField(max_length=200, verbose_name='In-Salon Product Name')),
                ('insProd_Desc', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('insProd_stockQty', models.IntegerField(verbose_name='Stock Quantity')),
                ('insProd_Price', models.FloatField(verbose_name='Price')),
            ],
        ),
    ]
