# Generated by Django 4.0.5 on 2022-07-01 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insalon_Products',
            new_name='Insalon_Product',
        ),
    ]
