# Generated by Django 4.0.5 on 2022-07-02 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_insalon_products_insalon_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insalon_Product',
            new_name='product',
        ),
    ]
