# Generated by Django 4.0.5 on 2022-07-02 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_insalon_product_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='Product_s',
        ),
    ]
