# Generated by Django 4.0.5 on 2022-07-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_product_product_s'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_s',
            new_name='Product',
        ),
    ]
