# Generated by Django 4.0.5 on 2022-07-05 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_product_s_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Name', models.CharField(max_length=200, verbose_name='Category')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='insProd_Name',
            field=models.CharField(max_length=200, verbose_name='Product Name'),
        ),
        migrations.AddField(
            model_name='product',
            name='Cat_Name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category'),
        ),
    ]
