# Generated by Django 4.0.5 on 2022-07-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_category_alter_product_insprod_name_product_cat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='insProd_Image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Product Image'),
        ),
    ]
