# Generated by Django 4.0.5 on 2022-07-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_product_insprod_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='insProd_Image',
            field=models.ImageField(default='placeholder-image.png', null=True, upload_to='', verbose_name='Product Image'),
        ),
    ]
