# Generated by Django 4.0.5 on 2022-07-07 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_product_insprod_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Cat_Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='insProd_Image',
            field=models.ImageField(default='placeholder-image.png', null=True, upload_to='product_images', verbose_name='Product Image'),
        ),
    ]
