# Generated by Django 4.0.5 on 2022-07-15 08:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_product_date_created_alter_product_cat_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='insProduct',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='Cat_Name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='ProdType_Name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Product Type'),
        ),
        migrations.CreateModel(
            name='otcProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otcProd_Name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('otcProd_Desc', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('otcProd_stockQty', models.IntegerField(verbose_name='Stock Quantity')),
                ('otcProd_Price', models.FloatField(verbose_name='Price')),
                ('otcProd_Image', models.ImageField(default='placeholder-image.png', null=True, upload_to='product_images', verbose_name='Product Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('Cat_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.category', verbose_name='Category')),
                ('ProdType_Name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.producttype', verbose_name='Product Type')),
            ],
        ),
    ]
