# Generated by Django 4.0.5 on 2022-07-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_product_insproduct_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insproduct',
            options={'verbose_name': 'In-salon Product'},
        ),
        migrations.AlterModelOptions(
            name='otcproduct',
            options={'verbose_name': 'Over-the-Counter Product'},
        ),
        migrations.RenameField(
            model_name='insproduct',
            old_name='insProd_Desc',
            new_name='Prod_Desc',
        ),
        migrations.RenameField(
            model_name='insproduct',
            old_name='insProd_Image',
            new_name='Prod_Image',
        ),
        migrations.RenameField(
            model_name='insproduct',
            old_name='insProd_Name',
            new_name='Prod_Name',
        ),
        migrations.RenameField(
            model_name='insproduct',
            old_name='insProd_Price',
            new_name='Prod_Price',
        ),
        migrations.RenameField(
            model_name='insproduct',
            old_name='insProd_stockQty',
            new_name='Prod_stockQty',
        ),
        migrations.RenameField(
            model_name='otcproduct',
            old_name='otcProd_Desc',
            new_name='Prod_Desc',
        ),
        migrations.RenameField(
            model_name='otcproduct',
            old_name='otcProd_Image',
            new_name='Prod_Image',
        ),
        migrations.RenameField(
            model_name='otcproduct',
            old_name='otcProd_Name',
            new_name='Prod_Name',
        ),
        migrations.RenameField(
            model_name='otcproduct',
            old_name='otcProd_Price',
            new_name='Prod_Price',
        ),
        migrations.RenameField(
            model_name='otcproduct',
            old_name='otcProd_stockQty',
            new_name='Prod_stockQty',
        ),
    ]
