# Generated by Django 4.0.5 on 2022-07-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_insproduct_options_alter_otcproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insproduct',
            name='Prod_stockQty',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Stock Quantity'),
        ),
        migrations.AlterField(
            model_name='otcproduct',
            name='Prod_Price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price'),
        ),
    ]
