# Generated by Django 4.0.5 on 2022-07-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_insproduct_prod_stockqty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insproduct',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='otcproduct',
            name='expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
