# Generated by Django 4.0.6 on 2022-07-16 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_customer_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_status', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Product Pickup Status',
                'verbose_name_plural': 'Product Pickup Statuses',
            },
        ),
        migrations.CreateModel(
            name='ProductPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickUpProd_Qty', models.IntegerField(verbose_name='Pickup Product Quantity')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.customer')),
                ('pickupstat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.pickupstatus')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.otcproduct')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pickUp_Date',
            field=models.DateTimeField(null=True, verbose_name='Pickup Date'),
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total Price')),
                ('product_pickupID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.productpickup')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.customer')),
                ('pickup_Date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.order')),
            ],
        ),
    ]
