# Generated by Django 4.0.6 on 2022-07-16 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_pickupstatus_productpickup_order_pickup_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpickup',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='productpickup',
            name='pickupstat',
        ),
        migrations.RemoveField(
            model_name='productpickup',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='pickupstat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.pickupstatus'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='product_pickupID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.order'),
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
        migrations.DeleteModel(
            name='ProductPickup',
        ),
    ]
