# Generated by Django 4.0.5 on 2022-07-16 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_productpickup_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickUp_Date',
            field=models.DateField(null=True, verbose_name='Pickup Date'),
        ),
    ]
